### ISSUE TITLE
更新最新的funcat到本地，安装以后运行测试程序报错

### ISSUE THREAD

**Issue by phoenixxz** [cedricporter/funcat#12]
select(
        lambda : (COUNT(CLOSE>0,0)>80) & ((HHV(CLOSE,80)-LLV(CLOSE,80))/LLV(CLOSE,80) <= 0.08),
        start_date=20170630,
        end_date=20170630,
        callback=callback,
    )

lambda : (COUNT(CLOSE>0,0)>80) & ((HHV(CLOSE,80)-LLV(CLOSE,80))/LLV(CLOSE,80) <= 0.08),
  File "/usr/lib/python2.7/site-packages/funcat-0.3.0-py2.7.egg/funcat/helper.py", line 40, in select
    order_book_id_list = data_backend.get_order_book_id_list()
                         └ <funcat.data.rqalpha_data_backend.RQAlphaDataBackend object at 0x32a11d0>
  File "/usr/lib/python2.7/site-packages/funcat-0.3.0-py2.7.egg/funcat/data/rqalpha_data_backend.py", line 68, in get_order_book_id_list
    if isinstance(insts, pd.DataFrame):
NameError: global name 'pd' is not defined

**Comment by better319** [comment]
解决了 吗？

**Comment by cedricporter** [comment]
昨天解决了，忘了更新 issue ，更新新版本就好了
