### ISSUE TITLE
VR指标用不了

### ISSUE THREAD

**Issue by pengfu008** [cedricporter/funcat#13]
funcat: 0.3.1, python: 3.5.3, 系统：macOS。

from funcat import *
from funcat.data.tushare_backend import TushareDataBackend
set_data_backend(TushareDataBackend())
set_start_date("2017-01-01")
S("600315")  # 设置当前关注股票
T("2017-06-30")  # 设置当前观察日期
print(VR())

IndexError: boolean index did not match indexed array along dimension 0; dimension is 119 but corresponding boolean dimension is 118

主要是用了REF(CLOSE, 1)后，series数量减1, 跟CLOSE比较后出错，望解决REF减1问题。

**Comment by cedricporter** [comment]
0.3.2 已经修复
