### ISSUE TITLE
运行funcat报错

### ISSUE THREAD

**Issue by zdco** [cedricporter/funcat#17]
## 1. funcat 的版本
最新版

## 2. Python 的版本
Python 3.6.2 x64

## 3. 是 Windows / Linux / MacOS or others?
Windows

## 4. 您出现问题对应的源码 / 或者能复现问题的简易代码
from funcat import *
print(C)

## 5. 您出现的错误堆栈日志信息
"F:\Program Files\Python\Python36\python.exe" D:/task/python/test/funcat.py
Traceback (most recent call last):
  File "D:/task/python/test/funcat.py", line 1, in <module>
    from funcat import *
  File "D:\task\python\test\funcat.py", line 3, in <module>
    print(C)
NameError: name 'C' is not defined

Process finished with exit code 1

**Comment by cedricporter** [comment]
你好，`D:/task/python/test/funcat.py` 您的脚本文件名和module重名了，你把您的 funcat.py 改成 funcat_test.py 之类的就可以了
