### ISSUE TITLE
关于安装的问题

### ISSUE THREAD

**Issue by better319** [cedricporter/funcat#3]
这个我安装怎么talib安装不了。。。能告知下平台吗？win7 32 python3.5 虚拟机， 还有个让我安装visualc++14 请帮我看下，拜托了！新手

**Comment by cedricporter** [comment]
Windows 环境下编译安装 bcolz 需要使用 Visual C++ Compiler，需要自行下载并安装 visual-cpp-build-tools，

如果觉得麻烦，也可以直接去 http://www.lfd.uci.edu/~gohlke/pythonlibs/#bcolz 下载相应版本的 bcolz wheel 包，直接安装编译后的 bcolz 版本。

**Comment by better319** [comment]
gei ge anconda de  anzhuang    jiaocheng .
