### ISSUE TITLE
funcat-tutorial 案例运行错误

### ISSUE THREAD

**Issue by better319** [cedricporter/funcat#4]
# 选出涨停股
select(
    lambda : C / C[1] - 1 >= 0.0995,
    start_date=20170104,
	end_date=20170104,
)
运行错误，
```
---------------------------
---------------------------
lambda : C / C[1] - 1 >= 0.0995,
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-19-88c2dd06ea5d> in <module>()
      3     lambda : C / C[1] - 1 >= 0.0995,
      4     start_date=20170104,
----> 5         end_date=20170105,
      6 )

D:\WinPython-32bit-3.5.3.0Qt5\python-3.5.3\lib\site-packages\funcat\helper.py in wrapper(*args, **kwargs)
     15         try:
     16             old_settings = np.seterr(all='ignore')
---> 17             return func(*args, **kwargs)
     18         finally:
     19             np.seterr(**old_settings)  # reset to default

D:\WinPython-32bit-3.5.3.0Qt5\python-3.5.3\lib\site-packages\funcat\helper.py in select(func, start_date, end_date, max_date, callback)
     36     data_backend = ExecutionContext.get_data_backend()
     37     order_book_id_list = data_backend.get_order_book_id_list()
---> 38     trading_dates = data_backend.get_trading_dates(start=data_backend.get_start_date(), end=max_date)
     39     for idx, date in enumerate(reversed(trading_dates)):
     40         if end_date and date > get_int_date(end_date):

D:\WinPython-32bit-3.5.3.0Qt5\python-3.5.3\lib\site-packages\funcat\data\tushare_backend.py in get_trading_dates(self, start, end)
     81         start = get_str_date_from_int(start)
     82         end = get_str_date_from_int(end)
---> 83         df = self.ts.get_k_data("000001", index=True, start=start, end=end)
     84         trading_dates = [get_int_date(date) for date in df.date.tolist()]
     85         return trading_dates

D:\WinPython-32bit-3.5.3.0Qt5\python-3.5.3\lib\site-packages\tushare\stock\trading.py in get_k_data(code, start, end, ktype, autype, index, retry_count, pause)
    673                                        symbol, code,
    674                                        index, ktype,
--> 675                                        retry_count, pause), 
    676                            ignore_index=True)
    677     if ktype not in ct.K_MIN_LABELS:

D:\WinPython-32bit-3.5.3.0Qt5\python-3.5.3\lib\site-packages\tushare\stock\trading.py in _get_k_data(url, dataflag, symbol, code, index, ktype, retry_count, pause)
    705                 js = json.loads(lines[0])
    706                 dataflag = dataflag if dataflag in list(js['data'][symbol].keys()) else ct.TT_K_TYPE[ktype.upper()]
--> 707                 if len(js['data'][symbol][dataflag][0]) == 6:
    708                     df = pd.DataFrame(js['data'][symbol][dataflag], 
    709                                   columns = ct.KLINE_TT_COLS_MINS)

IndexError: list index out of range
```

**Comment by better319** [comment]
我那个怎么不会画图啊。。。

**Comment by cedricporter** [comment]
这个应该是 tushare 的问题，您可以 `pip install -U tushare` 升级一下 tushare

**Comment by better319** [comment]
原来就升级了。，我用anaconda3的

**Comment by better319** [comment]
上面的都可以运行，就这个选股的有问题

**Comment by cedricporter** [comment]
直接用 `tushare.get_k_data("000001", index=True, start="2017-01-04", end="2017-01-04")` 试试？

**Comment by better319** [comment]
import后可以运行

**Comment by better319** [comment]
import tushare 
tushare.get_k_data("000001", index=True, start="2017-01-04", end="2017-01-04")  
可以运行

**Comment by better319** [comment]
date

open

close

high

low

volume

code



1
2017-01-04 3133.79 3158.79 3160.1 3130.11 167860850.0 sh000001

**Comment by cedricporter** [comment]
你现在重新运行 select 呢？

**Comment by better319** [comment]
lambda : C / C[1] - 1 >= 0.0995,




---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-78-366c9b4f2b12> in <module>()
      3     lambda : C / C[1] - 1 >= 0.0995,
      4     start_date=20170104,
----> 5         end_date=20170104,
      6 )

C:\Anaconda3\lib\site-packages\funcat\helper.py in wrapper(*args, **kwargs)
     15         try:
     16             old_settings = np.seterr(all='ignore')
---> 17             return func(*args, **kwargs)
     18         finally:
     19             np.seterr(**old_settings)  # reset to default

C:\Anaconda3\lib\site-packages\funcat\helper.py in select(func, start_date, end_date, max_date, callback)
     36     data_backend = ExecutionContext.get_data_backend()
     37     order_book_id_list = data_backend.get_order_book_id_list()
---> 38     trading_dates = data_backend.get_trading_dates(start=data_backend.get_start_date(), end=max_date)
     39     for idx, date in enumerate(reversed(trading_dates)):
     40         if end_date and date > get_int_date(end_date):

C:\Anaconda3\lib\site-packages\funcat\data\tushare_backend.py in get_trading_dates(self, start, end)
     81         start = get_str_date_from_int(start)
     82         end = get_str_date_from_int(end)
---> 83         df = self.ts.get_k_data("000001", index=True, start=start, end=end)
     84         trading_dates = [get_int_date(date) for date in df.date.tolist()]
     85         return trading_dates

C:\Anaconda3\lib\site-packages\tushare\stock\trading.py in get_k_data(code, start, end, ktype, autype, index, retry_count, pause)
    673                                        symbol, code,
    674                                        index, ktype,
--> 675                                        retry_count, pause), 
    676                            ignore_index=True)
    677     if ktype not in ct.K_MIN_LABELS:

C:\Anaconda3\lib\site-packages\tushare\stock\trading.py in _get_k_data(url, dataflag, symbol, code, index, ktype, retry_count, pause)
    705                 js = json.loads(lines[0])
    706                 dataflag = dataflag if dataflag in list(js['data'][symbol].keys()) else ct.TT_K_TYPE[ktype.upper()]
--> 707                 if len(js['data'][symbol][dataflag][0]) == 6:
    708                     df = pd.DataFrame(js['data'][symbol][dataflag], 
    709                                   columns = ct.KLINE_TT_COLS_MINS)

IndexError: list index out of range

**Comment by better319** [comment]
后面的选股也一样

**Comment by better319** [comment]
是不是你那里面时间格式有问题？

**Comment by cedricporter** [comment]
我之前用 tushare 的 0.6.18 是可以的，刚刚升级到 0.7.4 就报错了，我看看是啥问题

**Comment by better319** [comment]
恩，麻烦了，谢谢，这个库挺好的

**Comment by cedricporter** [comment]
发现确实 tushare 升级后行为比较诡异：

`ts.get_k_data("000029", start="20170104", end="20170104")`

**Comment by cedricporter** [comment]
目前可以先 `pip install tushare==0.6.8` ，降级一下就可以用了

**Comment by better319** [comment]
好的，谢谢

**Comment by better319** [comment]
改成0.6.8还是有问题；最后还是用了raphla


附代码：
from funcat.data.rqalpha_data_backend import RQAlphaDataBackend
set_data_backend(RQAlphaDataBackend("~/.rqalpha/bundle"))
set_data_backend(RQAlphaDataBackend(start_date="2014-07-01"))
S("000001.XSHG")  # 设置当前关注股票
T("2016-06-01")   # 设置当前观察日期

**Comment by better319** [comment]
你们那个ricequant里面什么时候把这个库加进去啊？

**Comment by cedricporter** [comment]
正在完善中，过段时间就加进去

**Comment by aweiu** [comment]
我改成了0.6.8也有问题，这样岂不是就没法获取实时数据了？

Error in sys.excepthook:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/utils.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/time_series.py", line 76, in value
    return self.series[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/utils.py", line 28, in wrapper
    raise FormulaException(e)
funcat.utils.FormulaException: index -1 is out of bounds for axis 0 with size 0

Original exception was:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/utils.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/time_series.py", line 76, in value
    return self.series[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print(O, H, L, C)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/time_series.py", line 161, in __repr__
    return str(self.value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/utils.py", line 28, in wrapper
    raise FormulaException(e)
funcat.utils.FormulaException: index -1 is out of bounds for axis 0 with size 0

**Comment by better319** [comment]
临时处理办法：
改用raphla作为数据源

附代码：
from funcat.data.rqalpha_data_backend import RQAlphaDataBackend
set_data_backend(RQAlphaDataBackend("~/.rqalpha/bundle"))
set_data_backend(RQAlphaDataBackend(start_date="2014-07-01"))
S("000001.XSHG") # 设置当前关注股票
T("2016-06-01") # 设置当前观察日期

**Comment by aweiu** [comment]
@better319 请问您是如何获取当前实时数据的？

**Comment by aweiu** [comment]
@better319 可以➕下我的Q吗？328080339 特别着急现在，卡在这里了。

**Comment by better319** [comment]
把这段话加载最前面就好了，重新运行下。你这个raphla的库要安装

**Comment by better319** [comment]
我都卡了20天了，别急，晚上我回去看下。下班了

**Comment by cedricporter** [comment]
IndexError: list index out of range 这个问题是新版本 tushare 的问题，建议可以先降级一下 tushare

https://github.com/waditu/tushare/issues/351

**Comment by aweiu** [comment]
@better319 @cedricporter 谢谢！
我已经降级了，现在是0.7.1 还是会报错
代码:
```
from funcat import *
# from funcat.data.rqalpha_data_backend import RQAlphaDataBackend
# set_data_backend(RQAlphaDataBackend())
from funcat.data.tushare_backend import TushareDataBackend
set_data_backend(TushareDataBackend())

T("20170419")
S("000001.XSHG")
print(O, H, L, C)
```

**Comment by cedricporter** [comment]
@aweiu 麻烦再确认下版本，我用0.6.8是ok
```
import tushare as ts; print(ts.__version__)
```

**Comment by aweiu** [comment]
@cedricporter 0.7.1 我是看了您发我的那个issues里有人说这个版本没问题我换的
现在我还安装不了0.6.1就很无奈了。。我再试试

**Comment by aweiu** [comment]
安装0.6.1得需要astropy，然后安装它会报错。大意是：
The C compiler used to compile Python gcc-4.2
我现在在想办法如何使用py3的c编译器

**Comment by aweiu** [comment]
@cedricporter 请问这个现在还有解吗？有没有可能是tushare那边请求的数据源出了问题

**Comment by cedricporter** [comment]
用 
```
pip install tushare==0.6.1
```
降级如果不行的话，可以使用另一个 Backend

```bash
from funcat.data.rqalpha_data_backend import RQAlphaDataBackend
from funcat import *

set_data_backend(RQAlphaDataBackend("~/.rqalpha/bundle"))
```

**Comment by aweiu** [comment]
@cedricporter 我试过 获取当天数据还是会报那个错误

**Comment by cedricporter** [comment]
那就先使用 RQAlphaDataBackend 吧

**Comment by aweiu** [comment]
那这样是不是意味着我就没有办法获取到当前的实时数据了，这就很蛋疼了。。
唉，真的特别想用您这个库，因为我只了解一些通达信的公式。。

**Comment by cedricporter** [comment]
你可以把你那边的报错贴一下看一下吧

**Comment by aweiu** [comment]
@cedricporter 
因为今天的股市交易结束了，我更新了今天的RQAlphaDataBackend数据，现在不会报错。只要没有当前数据，会报以下错误（因为今天已经过去了，所以您可以用明天的日期做测试一样会报那个错误）
代码如下（tushare 0.7.4）：
```
from funcat import *
from funcat.data.rqalpha_data_backend import RQAlphaDataBackend
set_data_backend(RQAlphaDataBackend())

T("20170419")
S("000001.XSHG")
print(O, H, L, C)
```
报错如下：
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/utils.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/time_series.py", line 76, in value
    return self.series[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/utils.py", line 28, in wrapper
    raise FormulaException(e)
funcat.utils.FormulaException: index -1 is out of bounds for axis 0 with size 0

Original exception was:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/utils.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/time_series.py", line 76, in value
    return self.series[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print(O, H, L, C)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/time_series.py", line 161, in __repr__
    return str(self.value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/funcat/utils.py", line 28, in wrapper
    raise FormulaException(e)
funcat.utils.FormulaException: index -1 is out of bounds for axis 0 with size 0

**Comment by cedricporter** [comment]
我看了你使用 RQAlphaDataBackend 这个错误，是因为没有当天的数据，错误提示不明确。你可以使用 

`rqalpha update_bundle` 更新以下数据。

另外可以 `pip install funcat==0.2.3` 升级一下，会改善错误提示。

另外看到 Tushare 升级到了 0.7.5 了，可能会没有问题了。

![image](https://cloud.githubusercontent.com/assets/1559563/25189757/b5ebeb80-255c-11e7-9ce0-8580d212e645.png)

**Comment by aweiu** [comment]
十分感谢您这么晚还回复我！
您这么说我好像理解了，如果是这样，我的疑惑就是那您这个库的select方法就是不能根据当前实时股价选股了是么？我之前猜想库可能会这么处理，优先会取本地取数据，然后本地数据和实时数据相差的部分会从tushare取，每次取完最新数据还会追加到本地数据中。因为不太熟悉Python，所以很难从您的源码中解读。另外，我那个报错也是我执行了update数据之后发生的，那时候可能是因为今天的数据还不全是吗？我在停盘之后又执行了一遍update才可以的。如果是这样，那就真的没办法基于当前股价选股了啊。

**Comment by cedricporter** [comment]
用默认的 TushareDataBackend 理论是可以盘中选股的。我记得 tushare 的 get_k_data 的最后一个 Bar 是动态更新的。

**Comment by aweiu** [comment]
好的。明天我再测试一遍！那不知道比如计算十日均价这种，如果是使用tushare，前九日的数据，在第一次请求之后会不会缓存到本地？还是说每次计算都得从服务器拉取？如果是这样，那效率肯定成问题的，毕竟三千多只股票筛选啊。
问了这么多都不好意思了，实在抱歉了，因为这些细节真的想搞清楚。

**Comment by cedricporter** [comment]
不过如果要做到高效地盘中实时选股，你需要自己实现一个 DataBackend ，使用本地历史数据（这个你可以使用RQAlpha的数据，后者自己把 tushare 的数据存到本地），再拼接 tushare.get_realtime_quotes 获取的当前实时的数据 得到动态更新的 K线。这样运行速度就可以大大提高。

tushare.get_realtime_quotes 这个是走新浪的数据，获取 3000只股票的盘口数据 1秒内可以搞定。

**Comment by aweiu** [comment]
OK!再次感谢，明天又有大活儿咯！您也早点休息了，晚安
