### ISSUE TITLE
是否支持周期变化?

### ISSUE THREAD

**Issue by phoenixxz** [cedricporter/funcat#6]
有月线或者周线的技术指标计算吗?

**Comment by cedricporter** [comment]
0.2.9 的 tushare 数据源是支持 周线、月线的。其他的数据源如果需要支持周线月线还需要自己去实现。

![image](https://user-images.githubusercontent.com/1559563/27768834-338dd0cc-5f4f-11e7-860c-0da8f1ccfa47.png)

**Comment by phoenixxz** [comment]
ok
