### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by phoenixxz** [cedricporter/funcat#7]
这是我写的一个测试代码片段，但是运行以后就会报错
from funcat.data.rqalpha_data_backend import RQAlphaDataBackend
from funcat import *

set_data_backend(RQAlphaDataBackend("~/.rqalpha/bundle"))

select(
    lambda : C / C[1] - 1 >= 0.0995,
    start_date=20170501,
	end_date=20170629,
)

错误提示如下：

lambda : C / C[1] - 1 >= 0.0995,
Traceback (most recent call last):
  File "3.py", line 9, in <module>
    end_date=20170629,
  File "/usr/lib/python2.7/site-packages/funcat-0.2.7-py2.7.egg/funcat/helper.py", line 17, in wrapper
    return func(*args, **kwargs)
           │     │       └ {'start_date': 20170501, 'end_date': 20170629}
           │     └ (<function <lambda> at 0x3b517d0>,)
           └ <function select at 0x32fc1b8>
  File "/usr/lib/python2.7/site-packages/funcat-0.2.7-py2.7.egg/funcat/helper.py", line 40, in select
    order_book_id_list = data_backend.get_order_book_id_list()
                         └ <funcat.data.rqalpha_data_backend.RQAlphaDataBackend object at 0x330ab10>
  File "/usr/lib/python2.7/site-packages/funcat-0.2.7-py2.7.egg/funcat/data/rqalpha_data_backend.py", line 67, in get_order_book_id_list
    return sorted(self.data_proxy.all_instruments('CS').order_book_id.tolist())
                  └ <funcat.data.rqalpha_data_backend.RQAlphaDataBackend object at 0x330ab10>
**AttributeError: 'list' object has no attribute 'order_book_id'**

**Comment by cedricporter** [comment]
请问您安装的是什么版本的 RQAlpha ，麻烦在 shell 中运行看看结果

 ```
rqalpha version
```

**Comment by phoenixxz** [comment]
def get_order_book_id_list(self):
        """获取所有的
        """
        #print self.data_proxy.all_instruments("CS")[1]

        for i in range(0, len(self.data_proxy.all_instruments("CS")), 1):
            self.order_bk_id.append(self.data_proxy.all_instruments("CS")[i].order_book_id)
        #return sorted(self.data_proxy.all_instruments("CS").order_book_id.tolist())
        return sorted(self.order_bk_id)

**Comment by cedricporter** [comment]
这个是因为最近 RQAlpha 的版本升级修改 data_proxy.all_instruments 的返回值，原来是返回 DataFrame，现在是返回 list ，所以就挂了，我加一下兼容吧

**Comment by cedricporter** [comment]
0.2.9 已经修复了，谢谢反馈
